version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:16.16.0

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: "Lint"
          command: npm run lint
      - run:
          name: "Check code format"
          command: npm run check-format                  
      - run:
          name: "Test"
          command: npm run test
      - run:
          name: "Build"
          command: npm run clean && npm run build
              
