import {
  CUSTOMER_NAME,
  REPORT_TYPE,
  SMART_CONTRACT_AUDIT_KEY,
  SOURCE_CODE_AUDIT_KEY,
  PRODUCT_NAME,
  REPORT_DATE,
  REPORT_VERSION,
  CUSTOMER_NAME_PLACEHOLDER,
  PRODUCT_NAME_PLACEHOLDER,
  COVER_FILE,
  COVER_FILE_NAME
} from './constants'

import { getReportDate } from './utils'

export const REPORT_METADATA = {
  [CUSTOMER_NAME]: CUSTOMER_NAME_PLACEHOLDER,
  [REPORT_TYPE]: `${SMART_CONTRACT_AUDIT_KEY} | ${SOURCE_CODE_AUDIT_KEY}`,
  [PRODUCT_NAME]: PRODUCT_NAME_PLACEHOLDER,
  [REPORT_DATE]: getReportDate(),
  [REPORT_VERSION]: 'vYYMMDD',
  [COVER_FILE]: COVER_FILE_NAME
}
